"""
Meta-Agent Generator.

Analyzes a user prompt, designs a dedicated agent blueprint,
and writes the code to agents/<agent_slug>/agent.py.
"""

import argparse
import os
import re
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI

AGENT_TEMPLATE = '''"""
{agent_title} Agent.
Auto-generated by Meta-Agent.
"""

import argparse
import base64
import os
import re
from typing import Annotated, TypedDict

from dotenv import load_dotenv
from fpdf import FPDF
from docx import Document
from pptx import Presentation
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph
from langgraph.graph.message import add_messages

load_dotenv()


class AgentState(TypedDict):
    messages: Annotated[list, add_messages]
    query: str
    report: str


def run_agent_task(state: AgentState) -> AgentState:
    gemini_key = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")
    
    llm = ChatOpenAI(
        model="gemini-2.5-flash",
        api_key=gemini_key,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
        temperature=0
    )

    system_prompt = (
        "{agent_instructions}\n"
        "IMPORTANT: Output ONLY the requested content as formatted Markdown. "
        "Do NOT write Python scripts or meta-explanations."
    )

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=state["query"]),
    ]

    response = llm.invoke(messages)
    return {{"report": response.content, "messages": [response]}}


# --- ON-DEMAND EXPORT FUNCTIONS ---

def export_pdf(text: str, filename: str = "report.pdf") -> str:
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_font("Helvetica", size=10)
    clean_text = text.encode('latin-1', 'replace').decode('latin-1')
    pdf.write(5, clean_text)
    pdf.output(filename)
    return filename


def export_docx(text: str, filename: str = "report.docx") -> str:
    doc = Document()
    doc.add_heading("Report", level=1)
    for line in text.split("\\n"):
        if line.strip():
            doc.add_paragraph(line)
    doc.save(filename)
    return filename


def handle_on_demand_export(prompt: str, report_text: str):
    prompt_lower = prompt.lower()
    generated_file = None

    if any(k in prompt_lower for k in ["docx", "word", "doc"]):
        generated_file = export_docx(report_text)
    elif "pdf" in prompt_lower:
        generated_file = export_pdf(report_text)

    if generated_file and os.path.exists(generated_file):
        with open(generated_file, "rb") as f:
            b64_str = base64.b64encode(f.read()).decode("utf-8")
            print(f"\\n---FILE_EXPORT_START:{{generated_file}}---")
            print(b64_str)
            print("---FILE_EXPORT_END---\\n")


def build_graph() -> StateGraph:
    graph = StateGraph(AgentState)
    graph.add_node("process", run_agent_task)
    graph.set_entry_point("process")
    graph.add_edge("process", END)
    return graph.compile()


def main():
    parser = argparse.ArgumentParser(description="{agent_title} Agent")
    parser.add_argument("--query", default=None, help="Task prompt")
    args = parser.parse_args()

    query = args.query or os.getenv("TASK_PROMPT") or "Execute agent task"

    agent = build_graph()
    result = agent.invoke({{"query": query, "messages": [], "report": ""}})

    report_content = result["report"]

    print("\\n---REPORT_START---")
    print(report_content)
    print("---REPORT_END---\\n")

    handle_on_demand_export(query, report_content)


if __name__ == "__main__":
    main()
'''


def generate_agent_slug(task_prompt: str, llm: ChatOpenAI) -> str:
    prompt = (
        f"Generate a short, lowercase, hyphenated slug for a specialist agent handling this task: '{task_prompt}'. "
        "Example: '21-quantum-computing-analyst'. Return ONLY the slug name, nothing else."
    )
    res = llm.invoke(prompt).content.strip().lower()
    return re.sub(r'[^a-z0-9\-]', '', res)


def generate_agent_instructions(task_prompt: str, llm: ChatOpenAI) -> str:
    prompt = (
        f"Write detailed System Instructions for an AI specialist designed to execute this task: '{task_prompt}'. "
        "Be specific about role, tone, output structure, and domain expertise required."
    )
    return llm.invoke(prompt).content.strip()


def create_agent(task_prompt: str):
    gemini_key = os.getenv("GEMINI_API_KEY") or os.getenv("OPENAI_API_KEY")
    llm = ChatOpenAI(
        model="gemini-2.5-flash",
        api_key=gemini_key,
        base_url="https://generativelanguage.googleapis.com/v1beta/openai/",
        temperature=0
    )

    slug = generate_agent_slug(task_prompt, llm)
    instructions = generate_agent_instructions(task_prompt, llm)

    agent_dir = os.path.join("agents", slug)
    os.makedirs(agent_dir, exist_ok=True)

    agent_code = AGENT_TEMPLATE.format(
        agent_title=slug.replace("-", " ").title(),
        agent_instructions=instructions.replace('"', '\\"'),
    )

    agent_path = os.path.join(agent_dir, "agent.py")
    with open(agent_path, "w", encoding="utf-8") as f:
        f.write(agent_code)

    req_path = os.path.join(agent_dir, "requirements.txt")
    with open(req_path, "w", encoding="utf-8") as f:
        f.write("langchain>=0.3.0\nlangchain-core>=0.3.0\nlangchain-openai>=0.2.0\nlanggraph>=0.2.20\npython-dotenv>=1.0.1\nfpdf2>=2.7.0\npython-docx>=1.1.0\npython-pptx>=0.6.23\n")

    print(f"CREATED_AGENT_SLUG:{slug}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--prompt", required=True, help="User prompt requiring an agent")
    args = parser.parse_args()

    create_agent(args.prompt)
